# Generated by Django 3.2.7 on 2021-10-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_house_photos_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_facilities',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_facilities', to='api_app.houses', verbose_name='Дом'),
        ),
    ]
