# Generated by Django 3.2.7 on 2021-10-31 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_house_facilities_house'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
