# Generated by Django 3.2.7 on 2021-10-31 19:06

import api_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_delete_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house_photos',
            name='file',
        ),
        migrations.AddField(
            model_name='house_photos',
            name='photo',
            field=models.ImageField(null=True, upload_to=api_app.models.nameFile),
        ),
    ]
